### ISSUE TITLE
Phantom points 

### ISSUE THREAD

**Issue by SchemingWeasels** [opravdin/lds-006-reverse-engineering#2]
I removed the 4 point median from the script to get the full resolution of the LiDAR, but I am getting some phantom points. Is this some known issue with the radar or did I just get a bad unit?

![image](https://user-images.githubusercontent.com/5172036/157067562-53fa8f54-43f9-4964-9e35-5738155e0501.png)

**Comment by SchemingWeasels** [comment]
After much messing around, I found a fix to this. Add a check to filter readings that have a 'reflectivity' value of 0.

The reflectivity here actually means the reflected or detected intensity. So anything that is that low would be inaccurate.

**Comment by opravdin** [comment]
Thank you, I will make some experiments with reflectivity value
